version: "3"
services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    environment:
      DATABASE_USER: your_db_user
      DATABASE_PASSWORD: your_db_password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: myapp_production
    ports:
      - "5432:5432"
