# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto

require 'google/protobuf'


descriptor_data = "\n\x12\x61uth_service.proto\x12\x04\x61uth\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t2G\n\x0b\x41uthService\x12\x38\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Auth
  TokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.TokenRequest").msgclass
  TokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.TokenResponse").msgclass
end
