# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth_service.proto for package 'auth'

require 'grpc'
require_relative 'auth_service_pb'

module Auth
  module AuthService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'auth.AuthService'

      rpc :ValidateToken, ::Auth::TokenRequest, ::Auth::TokenResponse
    end

    Stub = Service.rpc_stub_class
  end
end
